---
title: "Time Series on Daily Average Stock Scores"
author: "Autumn Li"
date: "2/28/2019"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Basic statistical analysis for stock scores Jul-Dec 2018

```{r}

stock = read.csv(file= "/ap5/AUDIT/liqiuy01/Statistical Research/time-series-data.csv", sep = ",", header = TRUE)
year = substr(stock$transactiondate,1,4)
month = substr(stock$transactiondate,5,6)
day = substr(stock$transactiondate,7,8)
stock_date = paste0(year,"/",month,"/",day)
date = as.Date(stock_date)
new_stock = cbind(as.numeric(stock$score),format(date,"%m/%d/%Y"))
new_stock = as.data.frame(new_stock)
colnames(new_stock)=c("score", "date")
means <- aggregate(as.numeric(score) ~ date, new_stock, mean)
head(means)
plot(means, ylab = "daily avg score", "stock daily average score")
abline(h = c(200, 380), col = c("blue", "red"))
counts<- aggregate(as.numeric(score) ~ date, new_stock,length)
head(counts)
plot(counts, ylab = "daily transaction count", main = "stock daily transaction count")
abline(h = c(200, 4000), col = c("blue", "red"))
```

## 2. Time Series Analysis on stock Average Scores from Jul-Dec 2018
```{r}
library(zoo)
zoo_score = zoo(means[,2], seq(from = as.Date("2018-07-02"), to = as.Date("2018-12-31"), by = 1))
plot.zoo(zoo_score,main="Time Series Plot of Score", ylab = "Daily Avg Score")

library(forecast)
model1 = auto.arima(zoo_score)
summary(model1)
tsdiag(model1,gof=20)
Box.test(model1$resid, lag = 20, type = "Ljung", fitdf = 2)### P-value=0.005837, there is serial correlation 
Box.test(model1$resid^2, lag = 20, type = "Ljung", fitdf = 2)####ARCH EFFECT, p_value = 0.1373, there is arch effect
```

## 3. Use Garch Models: in order to fix serial correlation and arch effect 
```{r}
require(rugarch)
spec7=ugarchspec(variance.model=list(model="fGARCH",submodel="TGARCH",garchOrder=c(1,1)),mean.model=list(armaOrder=c(2,2)),distribution.model="std")
fit7=ugarchfit(zoo_score,spec=spec7)
show(fit7)
plot(fit7, which=9)
spec71=ugarchspec(variance.model=list(model="sGARCH", garchOrder=c(1,1)),mean.model=list(armaOrder=c(2,2)),distribution.model="std")
fit71=ugarchfit(zoo_score,spec=spec71)
show(fit71)
plot(fit71, which=9)

spec6=ugarchspec(variance.model=list(model="sGARCH", garchOrder=c(1,1)),mean.model=list(armaOrder=c(2,2)),distribution.model="norm")
fit6=ugarchfit(zoo_score,spec=spec6)
show(fit6)
plot(fit6, which=9)
spec61=ugarchspec(variance.model=list(model="iGARCH", garchOrder=c(1,1)),mean.model=list(armaOrder=c(2,2)),distribution.model="std")
fit61=ugarchfit(zoo_score,spec=spec61)
show(fit61)
plot(fit71,which = 9)


```

## Forecast based on the model with best performance (sGarch on normal distribution)
```{r}
m71=ugarchfit(zoo_score, spec=spec6, out.sample=10)
forecast71=ugarchforecast(m71,data=NULL,n.ahead=31,n.roll=10, out.sample=200)
forecast71
plot(forecast71, which=2)
roll=ugarchroll(spec71, data=zoo_score, n.ahead=1, forecast.length=50, refit.every=10, refit.window=c("moving"))
plot(roll, which=4)

```

